services:
  - type: web
    runtime: static
    name: onecart-ecommerce-1
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
